version: "3"

services:
  backend:
    image: ghcr.io/7exp/craft-backend:latest
    container_name: craft-backend
    networks:
      - craft-network
    ports:
      - 5000:5000
    environment:
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - JWT_SECRET=
      - DATABASE_URL=mysql://root:abogoboga@10.1.1.13:3306/project_bacngkit
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
    #   interval: 60s
    #   timeout: 10s
    #   retries: 5
    restart: unless-stopped

networks:
  craft-network:
