version: "3"

services:
  backend:
    image: ghcr.io/7exp/craft-backend:latest
    container_name: craft-backend
    networks:
      - craft-network
    ports:
      - 5000:5000
    env_file:
      - stack.env
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
    #   interval: 60s
    #   timeout: 10s
    #   retries: 5
    restart: unless-stopped

networks:
  craft-network:
    name: craft-network
