version: "3"

services:
  backend:
    image: ghcr.io/7exp/craft-backend:latest
    container_name: craft-backend
    networks:
      - craft-network
      - tunnel
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
    #   interval: 60s
    #   timeout: 10s
    #   retries: 5
    restart: unless-stopped

  db:
    image: mariadb
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: abogoboga
      MYSQL_USER: root
      MYSQL_PASSWORD: abogoboga
    volumes:
      - ./compose/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - craft-network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      # - PMA_ARBITRARY=1
      - PMA_HOST=service-db
      - PMA_PORT=3306
    ports:
      - "888:80"
    networks:
      - craft-network
    depends_on:
      - db
    restart: unless-stopped

networks:
  craft-network:
    name: craft-network
  tunnel:
    external: true
