name: Deploy and Testing

on:
    workflow_run:
        workflows: ["Docker Build"]
        types: 
            - completed

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - name: Run dev environment
              run: |
                cd ~/backend
                git pull
                sudo docker-compose -f docker-compose-dev.yml pull
                sudo docker-compose -f docker-compose-dev.yml up -d
            - uses: matt-ball/newman-action@master
              with:
                collection: Postman/craft-backend-dev.json
                environment: Postman/CraftBackend.postman_environment.json
                delayRequest: 1000
                workingDir: ~/backend/Postman
            - name: Deploy to production
              run: |
                cd ~/backend
                git pull
                sudo sh deploy.sh
            
